import { ReactNode } from 'react';

import type { Metadata } from 'next';

import { Geist } from 'next/font/google';

import '@styles/reset.scss';
import '@styles/variables.scss';
import clsx from 'clsx';

import Cookie from '@components/cookie/Cookie';
import { Header } from '@components/header/Header';
import { getLanguage } from '@interfaces/dictionary';
import styles from '@styles/rootLayout.module.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Params = Promise<{ lng: string }>;

type Props = {
  children: ReactNode;
  params: Params;
};

export default async function RootLayout({ children, params }: Props) {
  const { lng } = await params;

  const language = getLanguage(lng);

  return (
    <html lang={language}>
      <body className={clsx(geistSans.variable, styles.root)}>
        <Header lng={language} />
        {children}
        <Cookie lng={language} />
      </body>
    </html>
  );
}
